import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import {
  AddUserToClassComponent,
  CreateClassComponent,
  CreateExerciseComponent,
  CreateSubjectComponent,
  DeleteExerciseComponent,
  FileMarksComponent,
  FileSendingComponent,
  FindClassComponent,
  GetClassComponent,
  GetClassStudentsComponent,
  GetMarkComponent,
  GetStudentFileComponent,
  GetTeacherFileComponent,
  MainPartComponent,
  SubjectViewComponent,
  SubjectsComponent,
  WorkRatingComponent,
  CreateGroupComponent,
  AddUserToGroupComponent,
  GetGroupComponent,
  GroupChatComponent,
  DeleteGroupComponent,
  ChatComponent,
  CreateChatComponent,
  GetChatsComponent,
  DeleteUserComponent,
  GetSubjectsComponent,
  DeleteSubjectComponent,
  UpdateSubjectComponent,
  CreateQuestionComponent,
  CreateEducationalTestComponent,
  GetTestsComponent,
  DeleteEducationalTestComponent,
  TestStepperComponent,
  TestEntranceComponent,
  CreateCategoryComponent,
  GetUserTestComponent,
  DeleteCategoryComponent,
  GetCategoriesComponent,
  CreateLessonComponent,
  CreateDayComponent,
  GetLessonsComponent,
  UpdateLessonComponent,
  DeleteLessonComponent,
  UpdateDayComponent,
  GetDayLessonsComponent,
  DeleteDayComponent,
  DeleteQuestionComponent,
  GetDayLessonsForAdminComponent,
  GetQuestionsComponent,
  UpdateQuestionComponent,
  UpdateExerciseComponent,
} from "./index"

const routes: Routes = [
  { path: 'main-part', component: MainPartComponent },
  { path: 'create-class', component: CreateClassComponent},
  { path: 'add-user-to-class', component: AddUserToClassComponent},
  { path: 'get-users-class/:className', component: GetClassStudentsComponent},
  { path: 'delete-user/:lastname/:firstname', component: DeleteUserComponent},
  { path: 'find-class',component: FindClassComponent},
  { path: 'get-class/:className',component: GetClassComponent},
  { path: 'create-subject',component: CreateSubjectComponent},
  { path: 'get-subjects', component: SubjectsComponent},
  { path: 'get-class-subjects/:className', component: GetSubjectsComponent},
  { path: 'update-subject/:userId', component: UpdateSubjectComponent},
  { path: 'subject-view/:subjectId', component: SubjectViewComponent},
  { path: 'delete-subject/:subjectName',component:DeleteSubjectComponent},
  { path: 'create-exercise', component: CreateExerciseComponent},
  { path: 'update-exercise/:exerciseId', component: UpdateExerciseComponent},
  { path: 'delete-exercise/:exerciseName',component:DeleteExerciseComponent},
  { path: 'work-rating/:exerciseId',component: WorkRatingComponent},
  { path: 'file-sending/:userId/:exerciseId', component: FileSendingComponent},
  { path: 'file-marks/:fileName',component: FileMarksComponent},
  { path: 'teacher-file/:exerciseId',component: GetTeacherFileComponent},
  { path: 'get-mark/:userId/:exerciseId',component: GetMarkComponent},
  { path: 'student-file/:userId/:exerciseId',component: GetStudentFileComponent},
  { path: 'create-group', component: CreateGroupComponent},
  { path: 'add-user-to-group', component: AddUserToGroupComponent},
  { path: 'get-group/:subjectId/:userId', component: GetGroupComponent},
  { path: 'group-chat/:groupId', component: GroupChatComponent},
  { path: 'delete-group/:groupName',component:DeleteGroupComponent},
  { path: 'create-chat/:userId', component: CreateChatComponent},
  { path: 'chat/:chatId', component: ChatComponent},
  { path: 'get-chats/:userId', component: GetChatsComponent},
  { path: 'create-question/:testId', component: CreateQuestionComponent},
  { path: 'get-questions/:testId', component: GetQuestionsComponent},
  { path: 'update-question/:questionId', component: UpdateQuestionComponent},
  { path: 'delete-question/:questionId', component: DeleteQuestionComponent},
  { path: 'get-categories/:testId', component: GetCategoriesComponent},
  { path: 'create-test/:subjectId', component: CreateEducationalTestComponent},
  { path: 'get-tests/:subjectId', component: GetTestsComponent},
  { path: 'delete-test/:testId', component: DeleteEducationalTestComponent},
  { path: 'create-category/:testId', component: CreateCategoryComponent},
  { path: 'delete-category/:categoryId', component: DeleteCategoryComponent},
  { path: 'test-stepper', component: TestStepperComponent},
  { path: 'assign-test/:testId/:userId', component: GetUserTestComponent},
  { path: 'create-lesson/:studentDayId', component: CreateLessonComponent},
  { path: 'create-studentDay', component: CreateDayComponent},
  { path: 'get-lessons/:userId', component: GetLessonsComponent},
  { path: 'get-day-lessons-for-admin', component: GetDayLessonsForAdminComponent},
  { path: 'get-day-lessons', component: GetDayLessonsComponent},
  { path: 'update-lesson/:lessonId', component: UpdateLessonComponent},
  { path: 'delete-lesson/:lessonOrder/:studentDayId', component: DeleteLessonComponent},
  { path: 'update-day/:studentDayId', component: UpdateDayComponent},
  { path: 'delete-day/:studentDayId/:day', component: DeleteDayComponent},
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class MainFuncRoutingModule { }
